>>> import wsd_code as wc
>>> import nltk
>>> nb_hard = wc.wsd_classifier(nltk.NaiveBayesClassifier.train, 'hard.pos', wc.wsd_word_features)
Reading data...
 Senses: HARD1 HARD2 HARD3
Training classifier...
Testing classifier...
Accuracy: 0.8108
